application: html5-demos-hrd
version: 1
runtime: python
api_version: 1

#default_expiration: "30d"

handlers:

- url: /google7833d615495f1112.html
  static_files: google7833d615495f1112.html
  upload: google7833d615495f1112.html

- url: /(.*\.(appcache|manifest))
  static_files: \1
  mime_type: text/cache-manifest
  upload: (.*\.(appcache|manifest))
  expiration: "0s"

- url: /(.*\.crx)
  static_files: \1
  mime_type: application/x-chrome-extension
  upload: (.*\.crx)

- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: http://www.html5rocks.com

- url: /bgnews
  static_dir: bgnews

#- url: /gddbr2010
#  static_files: static/gddbr2010-keynote/index.html
#  upload: /gddbr2010

#- url: /gddbr2010/(.*)
#  static_files: static/gddbr2010-keynote/\1
#  upload: /gddbr2010/(.*)

# Pretty URLs
- url: /shadowdom-visualizer\/?
  static_files: static/shadowdom-visualizer/index.html
  upload: /shadowdom-visualizer\/?

- url: /screenshare\/?
  static_files: static/getusermedia/screenshare.html
  upload: /screenshare\/?

- url: /hangouts\/?
  static_files: static/hangouts/index.html
  upload: /hangouts\/?

- url: /gangnam\/?
  static_files: static/webcomponents/demos/components/my-components/gangnam.html
  upload: /gangnam\/?

- url: /
  static_files: static/index.html
  upload: /static/index.html

- url: /admin.*
  script: $PYTHON_LIB/apphosting/ext/admin/__init__.py

- url: /.*
  script: main.py

#skip_files:
#- ^(.*/)?
#- ^(.*/)?.*~
#- ^(.*/)?.*\.py[co]
#- ^(.*/)?.*/RCS/.*
#- ^(.*/)?\..*
#- ^(.*/)?.*\.sh$
