application: html5-demos
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
- url: /static
  static_dir: static

#- url: /gddbr2010
#  static_files: static/gddbr2010-keynote/index.html
#  upload: /gddbr2010

#- url: /gddbr2010/(.*)
#  static_files: static/gddbr2010-keynote/\1
#  upload: /gddbr2010/(.*)

- url: /admin.*
  script: $PYTHON_LIB/apphosting/ext/admin/__init__.py

- url: /
  static_files: static/index.html
  upload: /static/index.html

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.sh$
